/// Flutter icons CustomIconsSvg
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIconsSvg
///      fonts:
///       - asset: fonts/CustomIconsSvg.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIconsSvg {
  CustomIconsSvg._();

  static const _kFontFam = 'CustomIconsSvg';
  static const _kFontPkg = null;

  static const IconData whatsapp = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marker_alt = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipsis_h = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hamburger = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartbeat = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paw = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lips = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_circle = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  
 static byName (String name){

    switch(name){
      case "bed":
        return bed;
        break;
      case "hamburger":
        return hamburger;
        break;
      case "dumbbell":
        return dumbbell;
        break;
      case "store":
        return store;
        break;
      case "heartbeat":
        return heartbeat;
        break;
      case "tools":
        return tools;
        break;
      case "paw":
        return paw;
        break;
      case "desktop":
        return desktop;
        break;
      case "lips":
        return lips;
        break;
    }
    
  }
  

}
